build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Mattermost"
  org.opencontainers.image.description: "Mattermost team communication platform for Home Assistant"
  org.opencontainers.image.source: "https://github.com/MichalTorma/ha-mattermost"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.documentation: "https://github.com/MichalTorma/ha-mattermost/blob/main/README.md"
args:
  MATTERMOST_VERSION: "9.11.0"
