name: "Mattermost Server"
description: "Mattermost team communication platform for Home Assistant"
version: "0.2.6"
slug: "mattermost"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: manual
hassio_api: true
hassio_role: default
host_network: false
privileged:
  - NET_ADMIN
ports:
  8065/tcp: 8065
ports_description:
  8065/tcp: "Mattermost Web Interface"
map:
  - config:rw
  - ssl:ro
  - media:rw
options:
  database_type: "postgres"
  database_host: "core-postgres"
  database_port: 5432
  database_name: "mattermost"
  database_user: "mattermost"
  database_password: ""
  site_url: ""
  enable_email: false
  smtp_server: ""
  smtp_port: 587
  smtp_username: ""
  smtp_password: ""
  smtp_enable_security: true
  admin_email: ""
  team_name: "Home Assistant Team"
  log_level: "INFO"
  enable_plugin_uploads: true
schema:
  database_type: "list(postgres|mysql)"
  database_host: "str"
  database_port: "port"
  database_name: "str"
  database_user: "str"
  database_password: "password"
  site_url: "url?"
  enable_email: "bool"
  smtp_server: "str?"
  smtp_port: "port?"
  smtp_username: "str?"
  smtp_password: "password?"
  smtp_enable_security: "bool"
  admin_email: "email?"
  team_name: "str"
  log_level: "list(DEBUG|INFO|WARN|ERROR)"
  enable_plugin_uploads: "bool"
webui: "http://[HOST]:[PORT:8065]"